### ISSUE TITLE
Want to create a new project with you 

### ISSUE THREAD

**Issue by Critickenjs** [lipishagupta/enigma#6]
Hi , im Critick , a french student  , me and my group want to collaborate with you to improve your game 
we can do more question , create a new version in french and maybe other language 
Its for a projet of my schools 
have a good day 
thanks :) 👍

**Comment by booba92iveyron** [comment]
hmmm im agree with u

**Comment by Critickenjs** [comment]
and  to change in HTML 5 , CSS and JavaScript

**Comment by lipishagupta** [comment]
Hi @Critickenjs and @booba92iveyron !
It would be great to collaborate with you. Do let me know your suggestions on how we can improve this game collectively.

**Comment by Critickenjs** [comment]
hi we will create  database where there will be 20 question 15 easy to code and 5 harder , 2 of us will code it in html and javascript
and the other 2 will continue in python

**Comment by Critickenjs** [comment]
we would like to separate the questions and the program , we want  to put the questions in a database and from that creates two versions of the game, one in python and the other in Html , javascript.
we will  start to learn the module csv
what do you think about it?
thanks 
have a good day

**Comment by lipishagupta** [comment]
Looks like a great idea!
Excited to work towards it.
Send me a pull request and then you can make the desired changes.
Let's build a great project!
